driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-5.11
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-7.11
  - name: debian-8.6
  - name: fedora-25
    run_list: yum::dnf_yum_compat
  - name: freebsd-10.3
    run_list:
      - freebsd::portsnap
      - freebsd::pkgng
  - name: freebsd-11
    run_list:
      - freebsd::portsnap
  - name: omnios-r151014
    driver:
      box: omnios/r151014
  - name: opensuse-13.2
  - name: opensuse-leap-42.1
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: solaris-11
    driver:
      box: chef/solaris-11
  - name: windows-2008r2-standard
    driver:
      box: chef/windows-server-2008r2-standard # private box in Chef's Atlas account
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard
  - name: macosx-10.10
    driver:
      box: chef/macosx-10.10 # private box in Chef's Atlas account
      provider: vmware_fusion
  - name: macosx-10.11
    driver:
      box: chef/macosx-10.11 # private box in Chef's Atlas account
      provider: vmware_fusion

suites:
  - name: default
    run_list: test::default
  - name: compile_time
    run_list: test::default
    attributes:
      build-essential:
        compile_time: true
