---
provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: centos-7-0-x64
  driver:
    name: digitalocean

- name: ubuntu-14-04-x64
  driver:
    name: digitalocean
  run_list:
  - recipe[apt]

- name: ubuntu-16-04-x64
  driver:
    name: digitalocean
  run_list:
  - recipe[apt]


suites:
  - name: default
    run_list:
      - recipe[rabbitmq::default]

  - name: default-use-distro-version
    run_list:
      - recipe[rabbitmq::default]
    attributes:
      rabbitmq:
        use_distro_version: true
    excludes: ["centos-7-0-x64"]
