driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.9
  - name: centos-7.3
  - name: debian-7.11
    run_list: apt::default
  - name: debian-8.8
    run_list: apt::default
  - name: fedora-25
  - name: opensuse-leap-42.2
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
- name: default
  run_list:
    - recipe[erlang]

- name: gui_tools
  run_list:
    - recipe[erlang]
  attributes:
    erlang:
      gui_tools: true
  excludes:
    - centos-6.9
    - centos-7.3
    - fedora-25

- name: esl
  run_list:
    - recipe[erlang::esl]
  excludes:
    - fedora-25
    - opensuse-42.2

- name: source
  run_list:
    - recipe[erlang::source]
