sudo: required
dist: trusty

# install the pre-release chef-dk.  Use chef-stable-trusty to install the stable release
addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

services: docker

# kitchen list -b | xargs -I {} echo "- INSTANCE={}"
env:
  matrix:
  - INSTANCE=default-centos-67
  - INSTANCE=default-centos-72
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=default-debian-7
  - INSTANCE=default-debian-8

  - INSTANCE=default-use-distro-version-ubuntu-1404
  - INSTANCE=default-use-distro-version-ubuntu-1604
  - INSTANCE=default-use-distro-version-debian-7
  - INSTANCE=default-use-distro-version-debian-8

  - INSTANCE=lwrps-centos-67
  - INSTANCE=lwrps-centos-72
  - INSTANCE=lwrps-ubuntu-1404
  - INSTANCE=lwrps-ubuntu-1604
  - INSTANCE=lwrps-debian-8

  - INSTANCE=cluster-centos-67
  - INSTANCE=cluster-centos-72
  - INSTANCE=cluster-ubuntu-1404
  - INSTANCE=cluster-ubuntu-1604
  - INSTANCE=cluster-debian-7
  - INSTANCE=cluster-debian-8

  - INSTANCE=default-force-yes-ubuntu-1404
  - INSTANCE=default-force-yes-ubuntu-1604
  - INSTANCE=default-force-yes-debian-7
  - INSTANCE=default-force-yes-debian-8

  - INSTANCE=default-force-yes-false-ubuntu-1404
  - INSTANCE=default-force-yes-false-ubuntu-1604
  - INSTANCE=default-force-yes-false-debian-7
  - INSTANCE=default-force-yes-false-debian-8

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen test ${INSTANCE}

matrix:
  include:
    - script:
      - /opt/chefdk/bin/chef exec rake
      env: UNIT_AND_LINT=1
